services:
  - type: web
    name: recetarioweb
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: pserve production.ini
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
