"""modelos iniciales

Revision ID: 9457a5f44195
Revises: 4a475edbc7b4
Create Date: 2025-05-21 15:01:05.143055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9457a5f44195'
down_revision = '4a475edbc7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='models', mysql_length={'name': 255})
    op.drop_table('models')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('value', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length={'name': 255})
    # ### end Alembic commands ###
